"""empty message

Revision ID: df2ad9720066
Revises: b41d34f92c0a
Create Date: 2020-01-15 17:53:58.329813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2ad9720066'
down_revision = 'b41d34f92c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('added_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'added_on')
    # ### end Alembic commands ###
